version: '3'
services:
    mariadb:
        #image: mariadb:latest
        container_name: soberitour-mariadb
        restart: 'on-failure'
        build:
            context: .
            dockerfile: ./docker/mariadb.Dockerfile
        environment:
            MARIADB_PORT_NUMBER: 3306
            MARIADB_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
            MARIADB_USER: www
            MARIADB_PASSWORD: www
        volumes:
            - ./var/lib/mysql:/var/lib/mysql
            - ./www:/var/www/html
            #- ./www/usr/db/:/docker-entrypoint-initdb.d/:ro
        command: mysqld --init-file="/var/www/html/usr/db/init.sql"

    php:
        # image: 'php:7.2-fpm'
        links:
            - mariadb
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        container_name: soberitour-php
        volumes:
            - './www/:/var/www/html'

    nginx:
        image: nginx:latest
        container_name: soberitour-nginx
        ports:
            - '8000:80'
            - '4443:443'
        links:
            - 'php'
        volumes:
            - './www:/var/www/html'
            - './config/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf'
            - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './config/nginx/snippets/:/etc/nginx/snippets/'
            - './config/nginx/conf:/etc/nginx/conf.d/'

    composer_installation:
        container_name: composer_installation
        build:
            context: .
            dockerfile: ./docker/composer.Dockerfile
        volumes:
            - ./www/:/var/www/html
        command: bash -c "composer install --no-scripts --no-autoloader --ignore-platform-reqs && composer dump-autoload"